language: node_js
node_js:
- 10
before_install:
- npm i -g npm@latest
- npm install
- npm run build
before_deploy:
  - npm run build
deploy:
  - provider: npm
    email: tilginis@gmail.com
    api_key:
      secure: DSRd98jNc1SouJtawaFIKnq3awwlXF0CAzcH091ctiIOr86ixftdlkk2+uuY6c6cpW6NVywhjbPzLM0RTGaJPm5TYSELuxOtiEoIYarJbnS9qNoNRA61Y+OgSmPrOh56SyZBXRzT26p0ZlgvSE0BNgpdsLFuQG/rVPjcOrRG9XSD3a79YC5YXz9+dF0zAQZYXUAwlav8M3y1ZttRKn062QWU0isTImNn5R1VJABWqeSeDKl5DPBTtYmpT0oby6789HE0Qs2jJ9wA+ZfLmUmbS3bE2NWQFYEU/OYGVtiJZc/+rSgdVxylAcQovrapSxUBgmfwjaoGRQi0IjwYezaMFqXvnXlzQpTXzVg3oS6EwJ9qfttSXKoio9slFUMp+djx50P6PZD3EkDXa80KMNZoicD32TtD89wlH+w5WeZyppg009bdTP6ShfSnrfbJGEhGcMyNWvf32CbO7uICa5mYHcJCJYVR+VWAJoaDf54wg2G7OkSi/xqMNTd/FZXXyaNmsd44keNLlJ09qjM7MCqiRD9IMVi9tYLPZS3+vtNz1xYurwL04OiYQ9C7rWinrmQnd/IaKL29Kqy/65lxMg1yu/7oPb08XNwnKW5rfyTWu3eHwVAooLWbm961GHmALSdrJY6ts0MmVr9i6WKRhelorNLc49aSEq3F2oTTn4SzUa8=
    on:
      tags: true
      repo: tomas862/regila-ui
      branch: master
    skip_cleanup: true
  - provider: pages
    local_dir: www
    skip_cleanup: true
    github_token: $GITHUB_REPO_TOKEN_MASTER
    keep_history: true
    on:
      branch: master

