language: node_js
node_js:
- 10
before_install:
- npm i -g npm@latest
- npm install
- npm run build
before_deploy:
  - npm run build
deploy:
  - provider: npm
    tag: next
    email: tilginis@gmail.com
    api_key: $NPM_TOKEN
    on:
      repo: tomas862/regila-ui
      branch: master
    skip_cleanup: true
  - provider: pages
    local_dir: www
    skip_cleanup: true
    github_token: $GITHUB_REPO_TOKEN_MASTER
    keep_history: true
    on:
      branch: master

